on:
  workflow_dispatch:

name: Archive smoothies

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          node app.js
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: smoothies
          path: smoothies.json
